### ISSUE TITLE
Anyway to display material icon in an ImageView?

### ISSUE THREAD

**Issue by anticafe** [code-mc/material-icon-lib#1]
I see `MaterialIconView` extends `ImageView`. So, is there anyway to display material icon in an existed `ImageView`?

**Comment by d4rken** [comment]
`MaterialDrawable` extends `Drawable`, just set it with `ImageView.setImageDrawable` ?

**Comment by code-mc** [comment]
I suggest you read through the README.md. Kind of a redundant question...
