### ISSUE TITLE
using icons within buttons 

### ISSUE THREAD

**Issue by Fshamri** [code-mc/material-icon-lib#10]
Hi,
How can i use icons within buttons of my my context menu layout. my context menu layout is like:
         
      <merge xmlns:android="http://schemas.android.com/apk/res/android">
          <Button
              android:id="@+id/btnShare"
              style="@style/ContextMenuButton"
              android:drawableRight="@android:drawable/ic_menu_share"
              android:text="@string/share.menu.share"
              android:textColor="@color/btn_context_menu_text_red" />
          <Button
              ............

**Comment by TakeoffAndroid** [comment]
@Fshamri 

STEP 1: Generate drawable runtime

Drawable shareDrawable = MaterialDrawableBuilder.with(context) // provide a context
        .setIcon(MaterialDrawableBuilder.IconValue.SHARE_VARIANT) // provide an icon
        .setColor(Color.WHITE) // set the icon color
        .setToActionbarSize() // set the icon size
    .build(); 

STEP 2: Then set drawable for button in runtime using

yourbutton. setCompoundDrawablesWithIntrinsicBounds( null, null, shareDrawable, null );

**Comment by code-mc** [comment]
Please read the manual or use above provided solution.
