### ISSUE TITLE
Some icons and code completion is not working

### ISSUE THREAD

**Issue by CoderHanXin** [code-mc/material-icon-lib#11]
When I set app:materialIcon="pen", it's OK.
But when I set app:materialIcon="calendar-text", I get error like this.

Error:(62, 35) String types not allowed (at 'materialIcon' with value 'calendar-text').

PS: Autocomplete is not work. And I put the font file inside the assets already.

**Comment by chteuchteu** [comment]
As you can see in the README, you have to use underscores (`_`) instead of dashes (`-`) as word separator. You will get rid of the `String types not allowed` error.

Are you sure that you put the font file inside the right assets directory?

**Comment by CoderHanXin** [comment]
@chteuchteu Thank you for your help.

I put font file inside src/main/assets.
LIVE previews works now, but code completion is still not working.

**Comment by code-mc** [comment]
Code complete not working is probably because you have something configured in your android studio settings that breaks the whole thing. First thing I hear about it anyways.

**Comment by CoderHanXin** [comment]
@code-mc Thank you, there is something wrong with my android sutdio.
I find answer from http://stackoverflow.com/questions/30684613/android-studio-xml-editor-autocomplete-not-working-with-support-libraries.
Code complete is OK now.
