### ISSUE TITLE
Add documentation about Toolbar menu

### ISSUE THREAD

**Issue by chteuchteu** [code-mc/material-icon-lib#13]
It seems that this library has a partial support for actionbar (`builder.setToActionbarSize();`). Can we use it the `Toolbar` component?

Toolbar icons are defined in `resources/menu` as following:

    <item
		android:id="@+id/menu_refresh"
		android:icon="@drawable/ic_action_navigation_refresh"
		app:showAsAction="ifRoom"
		android:title="@string/menu_refresh"/>

So we cannot blindly replace it with the `<net.steamcrafted.materialiconlib.MaterialIconView />` tag. Is there any way to do it in another way?

**Comment by code-mc** [comment]
No, things like that are unfortunately impossible to do with a 3rd party library. The method is just there because that is the most used icon size.
