### ISSUE TITLE
Using MaterialIconView in clickable parent makes ripple lag

### ISSUE THREAD

**Issue by chteuchteu** [code-mc/material-icon-lib#14]
When using MaterialIconView in a clickable parent (a ListView for example), the ripple effect happening when clicking the parent lags and seems to contain artifacts.

The ListView has only one element. Tried on a OnePlusOne with no application in the background (so lag isn't because of a heavy work happening in the background).

Using standard ImageView or ImageButton component works well.

**Comment by code-mc** [comment]
This might be due to a bug that is fixed as of 1.0.5. Please update your dependency and let me know if it improves the situation. (It did for me as far as I could tell)

**Comment by chteuchteu** [comment]
Thank you for the fix! I'll test it as soon as possible.
