### ISSUE TITLE
Any plan to update with new icons.

### ISSUE THREAD

**Issue by raviteja06** [code-mc/material-icon-lib#16]
Can you please give a small tutorial how we can update library with lastest ttf file from materialdesignicons.com? 

Thanks in advance. 

P.S: I like to contribute if you help me on how to get list of icons from ttf.

**Comment by code-mc** [comment]
It already is updated to the latest version (1.2.65)

**Comment by raviteja06** [comment]
Thanks. Just figured out, I was still using 1.0.3.

Best Regards,
Ravi Gadipudi

On Oct 24, 2015 8:31 PM, code-mc <notifications@github.com> wrote:

It already is updated to the latest version (1.2.65)
