### ISSUE TITLE
AutoComplete not working

### ISSUE THREAD

**Issue by CeJienAJPC** [code-mc/material-icon-lib#18]
I have added the .ttf file inside the Assets folder, added the gradle dependency. Unfortunately, I am unable to choose the required material icon.

In this (app:materialIcon="icon_name") xml code, I am unable to choose the required icon by the corresponding name. I have verified with various names. However, I am able to choose an icon by entering some integer value (app:materialIcon="1211"). Have I missed something somewhere? I retried the .ttf and gradle procedure but in vain. What seem to be the issue?

Regards

**Comment by code-mc** [comment]
Try updating android studio, I've had the same thing happen when I was on some non-final build.

**Comment by CeJienAJPC** [comment]
Thanks @code-mc. That helps. Working perfectly.
