### ISSUE TITLE
Not every icon is available for use - PART 2

### ISSUE THREAD

**Issue by crysan** [code-mc/material-icon-lib#20]
Not all the icons from https://materialdesignicons.com are getting synced into the project. Any ideas?
"image" and "image_broken_variant" still no
Regards

**Comment by code-mc** [comment]
I'm sorry but I can't add icons that aren't included in the icon pack download. Maybe the author of the pack forgot to include them, or they might just be in the pipeline for the next version!

**Comment by crysan** [comment]
Okay, wait.
