### ISSUE TITLE
MaterialIconColor with alpha channel

### ISSUE THREAD

**Issue by STFBEE** [code-mc/material-icon-lib#23]
Please, add support for transparent colors for icons. Right now it ignores alpha channel and fill icon with black (for #1f000000 for example)

**Comment by code-mc** [comment]
I remember not being able to get this to work when I first released it. But I'll have a look at it again, who knows :)

**Comment by code-mc** [comment]
Fixed!

https://github.com/code-mc/material-icon-lib/commit/d170fa709351946d151b4e7e83e23aa61ffebe36
