### ISSUE TITLE
Icons are not the same after update from 1.0.7 to 1.0.9

### ISSUE THREAD

**Issue by thelittlefireman** [code-mc/material-icon-lib#24]
After updating from 1.0.7 to 1.0.9 all icons that i set, are changed. for ex : i used the icon CALENDAR and now i get montains icon. I try clean build but nothing work, have you any idea ?

thanks 
Thomas

**Comment by code-mc** [comment]
If you update the library, also re-download the font-file and replace your previous one with the new one inside your app's assets.
