### ISSUE TITLE
Update icon list

### ISSUE THREAD

**Issue by vishaliiita** [code-mc/material-icon-lib#26]
There are few items in https://materialdesignicons.com/ which are not present in this library. Please include them.

**Comment by code-mc** [comment]
Just a heads up for anyone who's looking for an ETA for this: 1.6.50 just got released but contains a rather nasty bug that prevents me from updating the library. So no ETA for now unfortunately.

**Comment by franciscofranco** [comment]
@code-mc how do we make materialdesignicons fix their bug? Do they have a bug tracker or something?

**Comment by code-mc** [comment]
Just for update sake: fix has been scheduled for the next release of the icon font. So you can expect this library to be updated with a bunch of new icons whenever that update is released. https://github.com/Templarian/MaterialDesign/issues/1223

**Comment by code-mc** [comment]
New update was pushed this week, icons in this library now match the latest 1.7.12 version. (~200 new icons)

**Comment by franciscofranco** [comment]
Fucking awesome. Thank you.
