### ISSUE TITLE
Weird problem when creating a drawable with kotlin

### ISSUE THREAD

**Issue by wspl** [code-mc/material-icon-lib#27]
When I was trying to create a drawable icon in a kotlin project:
![image](https://cloud.githubusercontent.com/assets/2133311/15311009/dfa48588-1c28-11e6-846f-0f132a850e54.png)

```kotlin
val test1 = MaterialDrawableBuilder.with(applicationContext)
        .setIcon(MaterialDrawableBuilder.IconValue.WEATHER_RAINY)
        .setColor(Color.WHITE)

val test2 = test1.build()
```

Then Android Studio show a error:
`Type net.steamcrafted.materialiconlib.MaterialDrawableBuilder.MaterialDrawable! is inaccessible in this context due to: net.steamcrafted.materialiconlib.MaterialDrawableBuilder.MaterialDrawable!` 

I was only import `net.steamcrafted.materialiconlib.MaterialDrawableBuilder`

Is this a bug or my mistake?
Hope someone can solve this problem, very thanks!

**Comment by wspl** [comment]
I has found out a temporary solution to solve this problem.

Firstly, create a utils class with Java:
```java
package moe.impl.v2exnext.utils;

import android.graphics.drawable.Drawable;
import net.steamcrafted.materialiconlib.MaterialDrawableBuilder;

public class MaterialDrawableBuilderFix {
    public static Drawable build(MaterialDrawableBuilder materialDrawableBuilder){
        return materialDrawableBuilder.build();
    }
}
```

Then create a drawable with kotlin:
```kotlin
val icon = MaterialDrawableBuilderFix.build(MaterialDrawableBuilder
                .with(applicationContext)
                .setIcon(MaterialDrawableBuilder.IconValue.WEATHER_RAINY)
                .setColor(Color.WHITE))
```

This seems like a bug of kotlin.

**Comment by code-mc** [comment]
You also need to chain the build method, you can't save the intermediate builder, the intermediate representation class was made private to prevent anyone from doing that.
