### ISSUE TITLE
Android studio gradle build not working

### ISSUE THREAD

**Issue by TakeoffAndroid** [code-mc/material-icon-lib#3]
I am trying to use your library in project. But I am getting error when i add 
compile 'net.steamcrafted:materialiconlib:1.0.3' in build.gradle

Error getting:

Error:(33, 13) Failed to resolve: net.steamcrafted:materialiconlib:1.0.3

**Comment by code-mc** [comment]
I really don't know what would be causing this on my end. Have you tried "Clean project"?

**Comment by TakeoffAndroid** [comment]
Sorry it was the mistake of mine. Offline access checkbox was checked in my
gradle. So I cannot use your library. Now issue got fixed. Please close the
issue. Thanks for your support. I have refferred ur library even with some
of my friends.The only drawback is I couldn't use this for toolbar menu
icons. Please help me.
On Jul 28, 2015 1:34 AM, "code-mc" <notifications@github.com> wrote:

I really don't know what would be causing this on my end. Have you tried
"Clean project"?

—
Reply to this email directly or view it on GitHub
<https://github.com/code-mc/material-icon-lib/issues/3#issuecomment-125327622>
.
