### ISSUE TITLE
material-icon-lib with NavigationDrawer

### ISSUE THREAD

**Issue by feliperaymundo** [code-mc/material-icon-lib#30]
Is it possible to use the library when configuring the navigation drawer icons?

**Comment by code-mc** [comment]
Can you elaborate on which navigation drawer library are you using?

**Comment by feliperaymundo** [comment]
I have used the Google template within android studio. I think it uses android design library.

**Comment by code-mc** [comment]
Grab your NavigationView that you have defined inside your layout file. Then you can simply set icons in code:

```java
navigationView = (NavigationView) findViewById(R.id.nav);
navigationView.getMenu().findItem(R.id.your_menu_item_id).setIcon(yourMaterialIconDrawable);
```

That's all there is to it. This however isn't a question that belongs on github. This has most likely already been answered on stackoverflow.

**Comment by feliperaymundo** [comment]
Yes, but navigation drawer uses a menu inflation to set icons on items. Your library can be used for settings icons on menu's xml, and using your menu inflation. I would like to know how can I use icons like menu's xml, but for navigation drawer menu inflation.

**Comment by code-mc** [comment]
You most likely can't as I made the custom inflater specifically for toolbar menus. The navigation drawer uses menu XML files but uses a custom XML parser under the hood which would not play well with my custom menu inflater. It's a bit of an inconvenience that you have to set them in code but it is still better than not being able to use it at all :)

**Comment by feliperaymundo** [comment]
I agree. Thanks for replying.
