### ISSUE TITLE
Icon Color not changing in Samsung Galaxy Note 4

### ISSUE THREAD

**Issue by adisofttech** [code-mc/material-icon-lib#31]
hello ,
I am changing icon color at runtime its working good in other device but not in Samsung Galaxy Note 4 .
please provide solution for me.

**Comment by adisofttech** [comment]
device has android 6.0.1 (marshmallow)

**Comment by code-mc** [comment]
I'm afraid I don't have a note 4 so I won't be able to help you. Samsung devices however are known to have inconsistencies and making something work for every Samsung device can be a PITA.
