### ISSUE TITLE
Crash on API level 19 and below

### ISSUE THREAD

**Issue by thegppradeep** [code-mc/material-icon-lib#32]
Unable to solve this and not sure why this happens.
Here is my stack trace:

Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chalkstreet.app/com.chalkstreet.app.home.HomeActivity}: android.view.InflateException: Binary XML file line #385: Error inflating class net.steamcrafted.materialiconlib.MaterialIconView
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2338)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2390)
android.app.ActivityThread.access$800 (ActivityThread.java:151)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1321)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:5292)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:824)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:640)
dalvik.system.NativeStart.main (NativeStart.java)
arrow_drop_down
Caused by android.view.InflateException: Binary XML file line #385: Error inflating class net.steamcrafted.materialiconlib.MaterialIconView
android.view.LayoutInflater.createView (LayoutInflater.java:620)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:696)
android.view.LayoutInflater.rInflate (LayoutInflater.java:755)
android.view.LayoutInflater.rInflate (LayoutInflater.java:758)
android.view.LayoutInflater.rInflate (LayoutInflater.java:758)
android.view.LayoutInflater.parseInclude (LayoutInflater.java:839)
android.view.LayoutInflater.rInflate (LayoutInflater.java:745)
android.view.LayoutInflater.inflate (LayoutInflater.java:492)
android.view.LayoutInflater.inflate (LayoutInflater.java:397)
android.view.LayoutInflater.inflate (LayoutInflater.java:353)
android.support.v7.app.AppCompatDelegateImplV7.setContentView (AppCompatDelegateImplV7.java:280)
android.support.v7.app.AppCompatActivity.setContentView (AppCompatActivity.java:140)
com.chalkstreet.app.home.HomeActivity.onCreate (HomeActivity.java:334)
android.app.Activity.performCreate (Activity.java:5264)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1088)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2302)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2390)
android.app.ActivityThread.access$800 (ActivityThread.java:151)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1321)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:5292)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:824)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:640)
dalvik.system.NativeStart.main (NativeStart.java)
arrow_drop_down
Caused by java.lang.reflect.InvocationTargetException:
java.lang.reflect.Constructor.constructNative (Constructor.java)
java.lang.reflect.Constructor.newInstance (Constructor.java:423)
android.view.LayoutInflater.createView (LayoutInflater.java:594)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:696)
android.view.LayoutInflater.rInflate (LayoutInflater.java:755)
android.view.LayoutInflater.rInflate (LayoutInflater.java:758)
android.view.LayoutInflater.rInflate (LayoutInflater.java:758)
android.view.LayoutInflater.parseInclude (LayoutInflater.java:839)
android.view.LayoutInflater.rInflate (LayoutInflater.java:745)
android.view.LayoutInflater.inflate (LayoutInflater.java:492)
android.view.LayoutInflater.inflate (LayoutInflater.java:397)
android.view.LayoutInflater.inflate (LayoutInflater.java:353)
android.support.v7.app.AppCompatDelegateImplV7.setContentView (AppCompatDelegateImplV7.java:280)
android.support.v7.app.AppCompatActivity.setContentView (AppCompatActivity.java:140)
com.chalkstreet.app.home.HomeActivity.onCreate (HomeActivity.java:334)
android.app.Activity.performCreate (Activity.java:5264)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1088)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2302)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2390)
android.app.ActivityThread.access$800 (ActivityThread.java:151)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1321)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:5292)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:824)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:640)
dalvik.system.NativeStart.main (NativeStart.java)
arrow_drop_down
Caused by java.lang.NoClassDefFoundError: net.steamcrafted.materialiconlib.R$styleable
net.steamcrafted.materialiconlib.MaterialIconView.init (MaterialIconView.java:79)
net.steamcrafted.materialiconlib.MaterialIconView.<init> (MaterialIconView.java:34)
java.lang.reflect.Constructor.constructNative (Constructor.java)
java.lang.reflect.Constructor.newInstance (Constructor.java:423)
android.view.LayoutInflater.createView (LayoutInflater.java:594)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:696)
android.view.LayoutInflater.rInflate (LayoutInflater.java:755)
android.view.LayoutInflater.rInflate (LayoutInflater.java:758)
android.view.LayoutInflater.rInflate (LayoutInflater.java:758)
android.view.LayoutInflater.parseInclude (LayoutInflater.java:839)
android.view.LayoutInflater.rInflate (LayoutInflater.java:745)
android.view.LayoutInflater.inflate (LayoutInflater.java:492)
android.view.LayoutInflater.inflate (LayoutInflater.java:397)
android.view.LayoutInflater.inflate (LayoutInflater.java:353)
android.support.v7.app.AppCompatDelegateImplV7.setContentView (AppCompatDelegateImplV7.java:280)
android.support.v7.app.AppCompatActivity.setContentView (AppCompatActivity.java:140)
com.chalkstreet.app.home.HomeActivity.onCreate (HomeActivity.java:334)
android.app.Activity.performCreate (Activity.java:5264)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1088)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2302)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2390)
android.app.ActivityThread.access$800 (ActivityThread.java:151)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1321)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:5292)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:824)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:640)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by code-mc** [comment]
You'll have to clean your project, seems like the library is not imported correctly and some classes are missing.
