### ISSUE TITLE
MaterialDrawableBuilder does not care about Drawable.setBounds

### ISSUE THREAD

**Issue by metinkale38** [code-mc/material-icon-lib#34]
Hey,

the drawable created from the MaterialDrawableBuilder does not support the Drawable.setBounds, for example when used in custom views...

as workaround i had to create a new drawable for each size change and move the object with translate, which is not very optimal...

**Comment by code-mc** [comment]
Working on a proper bounds implementation right now. Can't believe nobody had this issue before...

**Comment by code-mc** [comment]
Fixed in 1.1.3
