### ISSUE TITLE
Attribute "materialIcon" already defined with incompatible format.

### ISSUE THREAD

**Issue by 456838** [code-mc/material-icon-lib#37]
Error:(2722) Attribute "materialIcon" already defined with incompatible format.
Error:(901) Original attribute defined here.
Error:(2722) Attribute "materialIcon" already defined with incompatible format.
Error:(901) Original attribute defined here.

ps:i crash with system attr , make the name diff can help

**Comment by code-mc** [comment]
You should use google for things like this, this is unrelated to the library
