### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by AsixJin** [code-mc/material-icon-lib#40]
The following icons are missing:
- periodic-table-co2
- periscope

**Comment by AsixJin** [comment]
Found another missing icon. Updated my initial post with those I found.

**Comment by code-mc** [comment]
I wouldn't spend too much time looking for missing items as the library hasn't been updated to v2.0.46 which means currently about 210 icons are missing.

**Comment by AsixJin** [comment]
Yeah I figured after I found two more. Any idea when this will be updated or how I may help?

**Comment by code-mc** [comment]
Updated to icons version 2.0.46 Sorry for the long wait.
