### ISSUE TITLE
On certain Samsung devices, there's an inflate issue using the "materialIconColor" attribute

### ISSUE THREAD

**Issue by xtcNet** [code-mc/material-icon-lib#44]
The issue stems from the format for this attribute in the attributes file being "color" instead of "color|reference". This is an isolated issue to certain devices, specifically Samsung devices. When manually importing the library files and editing this, it fixes it.

See https://stackoverflow.com/a/47221658

**Comment by code-mc** [comment]
Thanks, I'll try to get a fixed version on jcenter asap :)
