### ISSUE TITLE
Support font awesome?

### ISSUE THREAD

**Issue by peternguyen88** [code-mc/material-icon-lib#5]
This project is really great, do you have any plan to support font awesome as well? It will be great if everything is in a project.

**Comment by code-mc** [comment]
Maybe as an add-on? Adding both in the same project would get a bit bloaty and might introduce a lot of "duplicate" albeit differently designed icons. There also might be a library offering this already for font awesome as it has been around for much longer.

**Comment by peternguyen88** [comment]
Yes, there is. But this is the first lib that can support preview in visual studio which I find very convenient. It will be convenient to have the same thing like this for font awesome. I think we can create a different lib for font awesome or add it as a plugin would be great.
