### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by nitrico** [code-mc/material-icon-lib#6]
I assume that this lib is going to get updated with new icons from the community @ materialdesignicons.com. I'd like to know how often.

Thanks for the lib, it's very useful :)

**Comment by code-mc** [comment]
I'd like to keep it at a weekly update. Just checked the update log for the icons and it seems like they add new ones almost daily but that would be a bit crazy to keep up with!

**Comment by nitrico** [comment]
Fine! Thank you.

**Comment by Templarian** [comment]
Follow the twitter account at [MaterialIcons](https://twitter.com/materialicons) for notification on when the pack is updated. It's very random, but usually every 40 or 50 icons.

**Comment by nitrico** [comment]
There's a new release. Can you update it, please?

**Comment by code-mc** [comment]
Just wanted to let you know I have updated the icons to match the newly released version. Having a bit of a cold so I somehow missed the tweet.

**Comment by nitrico** [comment]
Great, thank you! :)
