### ISSUE TITLE
Suppport for ImageButton

### ISSUE THREAD

**Issue by Saketme** [code-mc/material-icon-lib#9]
Thank you for the fantastic library. Can we please have support for ImageButtons as well?

**Comment by TakeoffAndroid** [comment]
@saketme - you can use this library for TextView, Button, ImageButton, also by generating drawable runtime as like mentioned in the sample usuage. Please refer Readme. You have a method to generate dynamically using MaterialBuilder.

**Comment by code-mc** [comment]
@TakeoffAndroid @Saketme That would be a nice workaround I suppose.

**Comment by TakeoffAndroid** [comment]
@code-mc yeah sure. Thanks. please do support and have a glance of my repos. https://github.com/TakeoffAndroid/AppIntroAnimation. Kindly spread it among your friends.

**Comment by Saketme** [comment]
Ah you're right. I don't know why I skipped that part of Readme. Thank you!
